language: julia
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  # Turn off Neo4j auth
  - sed -i 's/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/' /etc/neo4j/neo4j.conf
  # Start Neo4j
  - sudo service neo4j start
