language: julia
julia:
  - release
  - nightly
notifications:
  email: false
services:
  - neo4j
before_install:
  - curl -H "Content-Type: application/json" -X POST -d '{"password":"neo4j"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password
