language: julia
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - sudo service neo4j start
  # Stupid hack - change the password then change it back
  - curl -v -X POST http://neo4j:neo4j@localhost:7474/user/neo4j/password -d"password=bogus"
  - curl -v -X POST http://neo4j:bogus@localhost:7474/user/neo4j/password -d"password=neo4j"
