language: julia
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  # Install Neo4j
  - sudo wget -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.org/repo stable/' | sudo tee /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -qq -y
  - sudo apt-get install neo4j -y
